unstable_features = true

style_edition = "2021"

max_width = 120

group_imports = "StdExternalCrate"
imports_granularity = "Crate"

normalize_comments = true

reorder_impl_items = true
condense_wildcard_suffixes = true
use_field_init_shorthand = true
format_macro_matchers = true
