exclude = [".cargo/config.toml"]
include = ["**/*.toml"]

[formatting]
column_width = 120

[[rule]]
include = ["**/Cargo.toml"]
keys = ["dependencies", "workspace.dependencies", "lints", "workspace.lints"]

[rule.formatting]
reorder_keys = true

[[rule]]
include = ["rustfmt.toml"]

[rule.formatting]
reorder_keys = true
