[alias]
xtask = "run --package xtask --"
xbuild = "xtask build"
asm = "xtask asm"
qemu = "xtask qemu"
env = "xtask env"
lint = "xtask lint"
ktest = "xtask ktest"
profiling = "xtask profiling"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
  # LLD linker
  #
  # You may need to install it:
  #
  # - Ubuntu: `sudo apt-get install lld clang`
  # - Fedora: `sudo dnf install lld clang`
  # - Arch: `sudo pacman -S lld clang`
  "-Clink-arg=-fuse-ld=lld",

  # Nightly
  "-Zshare-generics=y",
  "-Zthreads=0",
]

[target.x86_64-pc-windows-msvc]
# LLD linker
#
# You may need to install it:
#
# ```
# cargo install -f cargo-binutils
# rustup component add llvm-tools
# ```
linker = "rust-lld.exe"
rustdocflags = ["-Clinker=rust-lld.exe"]
rustflags = [
  # Nightly
  "-Zshare-generics=y", # This needs to be off if you use dynamic linking on Windows.
  "-Zthreads=0",
]